name: CI Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar Pruebas Automatizadas
        run: npm run test

      - name: Empaquetar Artefacto
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: legacy-billing-app
          path: .